---

- hosts: localhost
  connection: local
  become: yes
  vars:
    user: "{{ lookup('env', 'USER') }}"

  roles:
    - { role: zsh }
    - { role: gcc }
    - { role: cmake }
    - { role: clang }
    - { role: libcurl }
    - { role: gdb }
    - { role: valgrind }
    - { role: tmux }
    - { role: vim }
    - { role: boost }
    - { role: ruby }
    - { role: rbenv }
    - { role: bundler }
    - { role: peco }
    - { role: jq }
    - { role: direnv }
    - { role: go }
    - { role: nodenv }
    - { role: dotfiles }
    - { role: docker }
    - { role: docker-compose }
