- name: Dotfiles
  stat:
    path: /home/{{ user }}/dotfiles
  register: repos

- name: Clone dotfiles repository
  become_user: "{{ user }}"
  git:
    repo: https://github.com/simomu-github/dotfiles.git
    dest: /home/{{ user }}/dotfiles
    remote: origin
  when: not repos.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
