- name: check nodenv
  stat:
    path: /home/{{ user }}/.nodenv
  register: repos

- name: clone nodenv repository
  become_user: "{{ user }}"
  git:
    repo: https://github.com/nodenv/nodenv.git
    dest: /home/{{ user }}/.nodenv
    remote: origin
  when: not repos.stat.exists

- name: compile dynamic bash extension
  command: cd /home/{{ user }}/.nodenv && ./src/configure && make -C src
  become_user: "{{ user }}"
  when: not repos.stat.exists

- name: mkdir redis data directory
  file:
    path: /home/{{ user }}/.nodenv/plugins
    state: directory
    owner: "{{ user }}"
  when: not repos.stat.exists

- name: clone node build
  become_user: "{{ user }}"
  git:
    repo: https://github.com/nodenv/node-build.git
    dest: /home/{{ user }}/.nodenv/plugins/node-build
    remote: origin
  when: not repos.stat.exists
