- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
  tags: skip_test

- name: Install basic list of packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  tags: skip_test

- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu  {{ ansible_distribution_release  }} stable"
  tags: skip_test

- name: Install docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
  tags: skip_test

- name: Add user to docker group
  user:
    name: "{{ user }}"
    group: docker
  tags: skip_test

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes
  tags: skip_test
