- name: Install dependency
  apt:
    name: gnupg
    state: latest
    update_cache: yes

- name: Add repository
  apt_repository:
    repo: "ppa:jonathonf/vim"

- name: Ensure the vim are installed
  apt:
    name: vim
    state: latest
    update_cache: yes
