- name: check rbenv
  stat:
    path: /home/{{ user }}/.rbenv
  register: repos

- name: Clone rbenv repository
  become_user: "{{ user }}"
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /home/{{ user }}/.rbenv
    remote: origin
  when: not repos.stat.exists

- name: mkdir redis data directory
  file:
    path: /home/{{ user }}/.rbenv/plugins/ruby-build
    state: directory
    owner: "{{ user }}"
  when: not repos.stat.exists

- name: clone rbenv build
  become_user: "{{ user }}"
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/{{ user }}/.rbenv/plugins/ruby-build
    remote: origin
  when: not repos.stat.exists
